language: node_js
sudo: false
node_js:
  - "6"
  - "5"
  - "4"
install:
  - npm install
after_success:
  - npm run coverage
env:
  global:
  - secure: e0e2geSJ7CSgXX3HAWkGSmeEizu2yh67kNGFNNYMVPlsN60GvU2Ha0M4mibH4Np0pUFxmpXFZGnAE8HaHdFN9yJzRnIM1GjmFr6FsFzUWk8321yDI7yQTvUD7+08YeB6vb5mFhzLwpiz8lO8S+P56MbUnb1Csg4us7cWtYGHlY2K8M6WupGkrzZcBJ+OKZ6wCicDYNoioQeD8I8dFpbx/r9fo1Nps7MOZwLV+3/sDUgxD3pnX5Ik5yjkRqsEG85QTGTVg+ztgDXUHItlTt8PXq6HzD8z7bcH7AN/i9QjgddsmSFg391qsNo1ZzuAhfW1CKeXreItUVBPBQch1Gi+VKWOEL5MjasRMVJ0TZTZccmyIe1aRsyO3lPU8B6v4bIL1Vygx9yV+4D4+vfChT9/mMLnlIeiNyq6OQF8XzQVNEQGxgfmvhcDmhbMiA1E+QmCP2ADVWC0KHNjZoqPSKfgHRpiPJWFTBDL2NSE7VuNicE5lpkc2s/FoROGUEPNkf6gqqSmU5b2SLXitLMb4LUTCYnSr36eVNyHC/CM1xIO3ozEbi9dJo8zJO1HYeTPq2MdneCGHlR3jx5zaSedBXV/gnK/C/bXTIhJWCSRJuSaggqCbGQ+0JAJeyK7ffUXlXXkPPtQD77Whw7J7CTgglKJN837b5cNvDpjyj7huaiJ+6k=
  - secure: EirxiNsRGd9Q24hBF4ramWndOVw55QZuMY7duNwQc0e2gf2KgUh+EjnlBFhMMlIEdfAeDFUarRodnDTHm4awhJFDqoK+zWrLmaTKZGEtJ/FzcLK7SzrNRbZrTNPEp86ko26r04QPvpupnvnqGAgZ4+0E819JMhm+zn2Z/M/HITJz+4WLcUk0/qxycaNpycdpvkxRXv32xLHzXPTLuFRjLF1IWR3jeKilyUee6dWMrsLpz5+vUAZL7jFFdE5XBt7K60KwuyDHlYZwvhW5CfOPV7s3437rZYZ4dzBxXIJs4MK6I5XdWZf8BALAb79dJWy5a6JnQxXwRg8QCiQLLuAbR2i2GZfdROwQFErf7Sl94cDgSnRhZxwyttWCBjU+PmUn0+qMe3MYvyJ1XImPAwzb22to0r2S7IF0KIemmiX+C3k75ik8HX2iVsJqqmM9JCetwFVrY7OrEXHtp+mI/Pd1LcAx5U8H4ue7DsPUy2hVjYtH+sPB8+2kewuIr/VFSs8qQ7of4RSMeQQ1LqqJmDzpb8eUKtkLk9Hz9C5a3xPpauL75OIog7I8+HeNg6IoeDlIxPl7VdgzrQjPJLkA29kS6XjCEgY72mnmubvYZowq8HasGz9qlVMTsp1099Vd4cYnSdC1DG8GIytbmQt++fi3/fT6QXeCmuPnRro36/KN9Aw=
